---
# tasks file for miniconda
- name: Update miniconda
  shell: '"{{ item.path }}/{{ item.name }}/{{ miniconda_prefix }}/bin/conda" update conda -y -q'
  register: miniconda_update
  when: miniconda_update|bool
  changed_when: '"All requested packages already installed" in miniconda_update'
  loop: "{{ miniconda_env | d([]) }}"

- name: Create miniconda environment file
  copy:
    content: "{{ item.env | to_yaml(default_flow_style=False) }}"
    dest: "{{ item.path }}/{{ item.name }}/{{ miniconda_prefix }}/{{ item.name }}-environment.yml"
    owner: "{{ item.user | d('root') }}"
    group: "{{ item.group | d('root') }}"
  loop: "{{ miniconda_env | d([]) }}"

- include: environment.yml
  when: miniconda_env|length > 0

- name: Profile setup
  block:
    - name: Add miniconda to the PATH
      lineinfile:
        dest: "{{ item.profile_path | d('~/.bashrc') }}"
        line: export PATH={{ item.path }}/{{ item.name }}/{{ miniconda_prefix }}/bin:$PATH
        owner: "{{ item.user | d('root') }}"
        group: "{{ item.group | d('root') }}"
        state: present
      when: item.deploy_profile_mode == 'update'
      loop: "{{ miniconda_env | d([]) }}"

    - name: Create miniconda profile
      template:
        src: "{{ item.profile_template | d('miniconda.sh.j2') }}"
        dest: "{{ item.profile_path | d('/etc/profile.d/miniconda.sh') }}"
        mode: "{{ item.profile_mode | d('0644') }}"
      when: item.deploy_profile_mode == 'template'
      loop: "{{ miniconda_env | d([]) }}"
  when: item.deploy_profile_mode is defined

- name: Change miniconda directory permissions
  file:
    path: "{{ item.path }}/{{ item.name }}/{{ miniconda_prefix }}"
    state: directory
    owner: "{{ item.user | d('root') }}"
    group: "{{ item.group | d('root') }}"
    recurse: yes
  loop: "{{ miniconda_env | d([]) }}"