---
- name: Create miniconda environment
  shell: '"{{ item.path }}/{{ item.name }}/{{ miniconda_prefix }}/bin/conda" env create -f "{{ item.path }}/{{ item.name }}/{{ miniconda_prefix }}/{{ item.name }}-environment.yml" {{ item.create_opts | d(omit)}}'
  args:
    creates: '{{ item.path }}/{{ item.name }}/{{ miniconda_prefix }}/envs/{{ item.env.name }}'
  register: miniconda_env_create
  loop: "{{ miniconda_env | d([]) }}"

- name: Update miniconda environment
  shell: '"{{ item.path }}/{{ item.name }}/{{ miniconda_prefix }}/bin/conda" env update -n "{{ item.name }}" -f "{{ item.path }}/{{ item.name }}/{{ miniconda_prefix }}/{{ item.name }}-environment.yml" {{ item.update_opts | d(omit) }}'
  register: miniconda_env_update
  changed_when: '"COMPLETE" in miniconda_env_update.stdout'
  loop: "{{ miniconda_env_create.results | selectattr('stdout', 'search', 'skipped') | map(attribute='item') | list }}"