---
# tasks file for miniconda
- name: Install miniconda prereqs
  include_tasks: prereqs.yml
  when: miniconda_manage_dependencies

- name: Setup miniconda users
  include_tasks: users.yml
  when: miniconda_manage_users

- name: Install miniconda
  include_tasks: install.yml

- name: Configure miniconda
  include_tasks: configure.yml
