---
- name: Install Debian packages
  apt:
    pkg: "{{ miniconda_packages['Debian'] }}"
    state: present
  when: ansible_os_family in [ "Debian" ]

- name: Install Redhat packages
  yum:
    name: "{{ miniconda_packages['Redhat'] }}"
    state: present
  when: ansible_os_family in [ "Redhat" ]
